development:
  sessions:
    default:
      database: dummy_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: dummy_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
